HW2 is completed
dijer/otus-go pull request #2
Opened 2024-08-12 19:36 UTC by dijer

2024-08-13 08:48 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако возвращаю задачу на доработку, потому что не хватает новых юнит-тестов
Итого: 5 баллов из 10

Прошу при создании PR использовать шаблон

2024-08-13 08:48 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(inputRunes); i++ {
Удобно использовать цикл-range по строке и не обращаться к элементам по индексу

2024-08-13 08:48 UTC, agneum commented on hw02_unpack_string/unpack.go
> +			if nextCharNumber, err := strconv.Atoi(nextChar); err == nil {
Думаю, что следует обработать случай, когда err != nil

2024-08-13 08:48 UTC, agneum commented on hw02_unpack_string/unpack_test.go
> +	//nolint:depguard
Можно создать конфиг для depguard, чтобы не добавлять исключения в коде: https://github.com/OpenPeeDeeP/depguard?tab=readme-ov-file#config

2024-08-13 08:48 UTC, agneum commented on hw02_unpack_string/unpack_test.go
Не хватает новых юнит-тестов

2024-08-13 19:11 UTC, dijer commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(inputRunes); i++ {
fxd

2024-08-13 19:14 UTC, dijer commented on hw02_unpack_string/unpack_test.go
> +	//nolint:depguard
fxd

2024-08-13 19:14 UTC, dijer commented on hw02_unpack_string/unpack.go
> +			if nextCharNumber, err := strconv.Atoi(nextChar); err == nil {
добавил

2024-08-13 19:14 UTC, dijer commented on hw02_unpack_string/unpack_test.go
написал

2024-08-13 19:16 UTC, dijer commented
@agneum Все поправил, проверь, пожалуйста

2024-08-15 04:58 UTC, agneum requested changes
Спасибо за правки, хорошая работа.
Однако не могу принять, потому что в репозитории отключены все линтеры

2024-08-15 04:58 UTC, agneum commented on .golangci.yml
> +      - github.com/stretchr/testify
В репозитории нельзя отключать линтеры.
Для depguard-конфигурации можно использовать специальный файл

2024-08-15 18:17 UTC, dijer commented on .golangci.yml
> +      - github.com/stretchr/testify
поправил

2024-08-16 07:41 UTC, agneum approved these changes
Спасибо, хорошая работа.
Принято

2024-08-16 10:30 UTC, merged