hw04_lru_cache completed
dijer/otus-go pull request #4
Opened 2024-08-26 19:51 UTC by dijer

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-08-28 08:45 UTC, agneum requested changes
Спасибо за вариант решения, хорошая работа.
Однако текущая реализация не может быть использована длительное время из-за утечки памяти и переполнения счётчика, возвращаю задачу на доработку.

2024-08-28 08:45 UTC, agneum commented on hw04_lru_cache/cache.go
> +	if c.items[key] != nil {
Корректнее проверять наличие ключа, используя специальный синтаксис `value, ok := c.items[key]`
nil - валидное значение, которое может храниться в мапе

2024-08-28 08:45 UTC, agneum commented on hw04_lru_cache/cache.go
> +	c.keys = append(c.keys, key)
Выглядит так, что ключи только добавляются и никогда не удаляются, хотя элемент уже может быть вытеснен из кэша.

2024-08-28 08:45 UTC, agneum commented on hw04_lru_cache/cache.go
> +		c.keyIndex++
Использование специального индекса не предусматривает случай переполнения значения счётчика.

Рекомендовал бы в элементе кэша хранить не только значение, но и ключ, по которому можно идентифицировать этот элемент

2024-08-28 08:45 UTC, agneum commented on hw04_lru_cache/list.go
> +		Prev:  nil,
Поля с zero-value можно не указывать

2024-08-29 16:56 UTC, dijer commented on hw04_lru_cache/cache.go
> +	if c.items[key] != nil {
поправил

2024-08-29 16:56 UTC, dijer commented on hw04_lru_cache/cache.go
> +	c.keys = append(c.keys, key)
удалил ключи

2024-08-29 16:56 UTC, dijer commented on hw04_lru_cache/cache.go
> +		c.keyIndex++
доработал

2024-08-29 16:56 UTC, dijer commented on hw04_lru_cache/list.go
> +		Prev:  nil,
удалил

2024-08-30 06:06 UTC, agneum approved these changes
Спасибо за правки, выглядит здорово
Итого: 10 баллов из 10. Принято

2024-09-02 20:39 UTC, merged